name: Code analysis and tests

on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
  push:
    branches-ignore:
      - develop
      - main
      - 'release/**'
jobs:
  code_analysis_and_tests:
    name: Code analysis and tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.0'
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Analyze error
        run: flutter analyze

      - name: Analyze code formatting
        run: flutter format --set-exit-if-changed .

      - name: Run unit tests and widget tests
        run: flutter test --coverage

      - name: Upload code coverage to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
